### ISSUE TITLE
Così torna anche 0 (deve tornare minimo 1)

### ISSUE THREAD

**Issue by kstatua-alpenite** [frankekko91/spotify-skin#2]
https://github.com/frankekko91/spotify-skin/blob/ac435588f915c3cc3b2f5fcaece8953196e311be/file-di-git.js#L1-L4

**Comment by frankekko91** [comment]
var banchiereCarta1 = Math.floor((Math.random() * 10) + 1);
var banchiereCarta2 = Math.floor((Math.random() * 10) + 1); 
var playerCarta1 = Math.floor((Math.random() * 10) + 1);
var playerCarta2 = Math.floor((Math.random() * 10) + 1);
